#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

autoRegenerate="true"

repoDir=$(pwd)

for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '^.*/cmd/.*\.go$'; then

        docDate=$(stat -c %X docs/cli/git_hooks.md)

        if [ "$((docDate + 60 * 5))" -lt "$(date +%s)" ]; then
            if [ "$autoRegenerate" = "true" ]; then
                # shellcheck disable=SC2015
                cd githooks && "scripts/build-doc.sh" || {
                    echo "! Doc regeneration failed!"
                    exit 1
                }

                git add "$repoDir/docs/cli/"*

                echo "Docs regenerated."
            else
                echo "! You need to regenerate the CLI docs (its too old)!"
                exit 1
            fi
        fi
    fi
done

echo "* CLI docs is up to date"
