#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

autoRegenerate="true"

repoDir="$DIR/../.."

cd "$repoDir" || exit 1

if command -v "gstat" &>/dev/null; then
    statCmd="gstat"
else
    statCmd="stat"
fi

for file in $STAGED_FILES; do
    if echo "$file" | grep -qE '^.*/cmd/.*\.go$'; then

        docDate=$("$statCmd" -c %X "$repoDir/docs/cli/git_hooks.md")

        if [ "$((docDate + 2 * 5))" -lt "$(date +%s)" ]; then
            if [ "$autoRegenerate" = "true" ]; then
                # shellcheck disable=SC2015
                cd githooks && "scripts/build-doc.sh" || {
                    echo "! Doc regeneration failed!" >&2
                    exit 1
                }

                git add "$repoDir/docs/cli/"*

                echo "Docs regenerated." >&2
            else
                echo "! You need to regenerate the CLI docs (its too old)!" >&2
                exit 1
            fi
        fi
    fi
done

echo "* CLI docs is up to date" >&2
