#!/usr/bin/env bash
set -e
set -u

if ! command -v golangci-lint >/dev/null 2>&1; then
  echo "! golangci-lint - not installed" >&2
  exit 1
fi

cd githooks || exit 1

if
  CGO_ENABLED=0 golangci-lint run \
    --exclude-dirs /usr/local/go \
    -E godot \
    -E gomnd \
    -E goconst \
    -E gochecknoinits \
    -E nlreturn \
    -E misspell \
    -E lll \
    -E exportloopref \
    -E gocritic \
    --max-same-issues 0 ./...
then
  echo "* golangci-lint OK" >&2
else
  echo "! golangci-lint problems detected" >&2
  exit 1
fi
