#!/usr/bin/env bash
# shellcheck disable=SC2153
if [ -n "${STAGED_FILES}" ]; then
    echo "* Staged files:" >&2

    for STAGED_FILE in $STAGED_FILES; do
        echo "  - $STAGED_FILE" >&2
    done
fi
