#!/usr/bin/env bash
# shellcheck disable=SC1091
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0

checkSetX() {
    LINES=$(grep -rnHE "(set.*[-+]x)" "$FILE")

    if [ -n "$LINES" ]; then
        echo "! Found \`set -x\`: $LINES" >&2
        SUCCESS=1
    fi
}

for FILE in $STAGED_FILES; do
    echo "$FILE" | grep -qE '\.sh$' && checkSetX "$FILE"
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No \`set -x\` found" >&2
else
    exit "$SUCCESS"
fi