#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

success=0

checkSetX() {
    lines=$(grep -rnHE "(set.*[-+]x)" "$file") || true

    if [ -n "$lines" ]; then
        echo "! Found \`set -x\`: $lines" >&2
        success=1
    fi
}

for file in $STAGED_FILES; do
    echo "$file" | grep -qE '\.sh$' && checkSetX "$file"
done

if [ "$success" = "0" ]; then
    echo "* No \`set -x\` found" >&2
else
    exit "$success"
fi
