#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

success=0

checkTab() {
    local lines
    lines=$(grep -rnH "$(printf '\t')" "$1") || true

    if [ -n "$lines" ]; then
        echo "! Tab character found in: $lines" >&2
        success=1
    fi
}

for file in $STAGED_FILES; do
    if echo "$file" | grep -qvE "(githooks|docs)/.*$"; then
        checkTab "$file"
    fi
done

if [ "$success" = "0" ]; then
    echo "* No tab characters detected" >&2
else
    exit "$success"
fi
