#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

success=0

checkTodo() {
    local lines
    lines=$(grep -rnHE "(TODO|FIXME)" "$1") || true

    if [ -n "$lines" ]; then
        echo "! TODO or FIXME found in: $lines" >&2
        success=1
    fi
}

for file in $STAGED_FILES; do
    if echo "$file" | grep -qvE '(cover/|pre-commit/no-todo-or-fixme|\.md)'; then
        checkTodo "$file"
    fi
done

if [ "$success" = "0" ]; then
    echo "* No TODO or FIXME detected" >&2
else
    exit "$success"
fi
