#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

if ! shellcheck --version >/dev/null 2>&1; then
    echo "- Skipping shellcheck - not installed" >&2
    exit 0
fi

success=0
for file in $STAGED_FILES; do
    if echo "$file" | grep -qE '\.sh$' &&
        ! shellcheck "$file"; then
        echo "! shellcheck problems detected in: $file" >&2
        success=1
    fi
done

if [ "$success" = "0" ]; then
    echo "* shellcheck OK" >&2
else
    exit "$success"
fi
