#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

if ! shellcheck --version >/dev/null 2>&1; then
    echo "- Skipping shellcheck - not installed" >&2
    exit 0
fi

SUCCESS=0
for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '\.sh$' &&
        ! shellcheck "$FILE"; then
        echo "! shellcheck problems detected in: $FILE" >&2
        SUCCESS=1
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* shellcheck OK" >&2
else
    exit "$SUCCESS"
fi
