#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

success=0
for file in $STAGED_FILES; do
    if echo "$file" | grep -qE '\.sh$' &&
        echo "$file" | grep -qv '/cover/' &&
        grep -nrHE 'shellcheck.*disable' "$file" | grep -v '# shellcheck disable=SC'; then
        echo "! Wrong shellcheck ignored format: use \`# shellcheck disable=SCnnnn\` in $file"
        success=1
    fi
done

if [ "$success" = "0" ]; then
    echo "* No shellcheck ignore format issues found" >&2
else
    exit 1
fi
