#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

if ! shfmt --version >/dev/null 2>&1; then
    echo "- Skipping shfmt - not installed" >&2
    exit 0
fi

SUCCESS=0
for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE "\.sh$" &&
        ! shfmt -p -d -i 4 "$FILE"; then
        echo "! shfmt problems detected in $FILE" >&2
        SUCCESS=1
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* shfmt OK" >&2
else
    exit "$SUCCESS"
fi
