#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
set -u

DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

if ! shfmt --version >/dev/null 2>&1; then
    echo "- Skipping shfmt - not installed" >&2
    exit 0
fi

success=0
for file in $STAGED_FILES; do
    if echo "$file" | grep -qE "\.sh$" &&
        ! shfmt -d -i 4 "$file"; then
        echo "! shfmt problems detected in $file" >&2
        success=1
    fi
done

if [ "$success" = "0" ]; then
    echo "* shfmt OK" >&2
else
    exit "$success"
fi
