// +build tools

package main

import (
	"gabyx/githooks/apps/dialog/cmd"
	dcm "gabyx/githooks/apps/dialog/cmd/common"
	cm "gabyx/githooks/common"
	"gabyx/githooks/git"
	strs "gabyx/githooks/strings"
	"io/ioutil"
	"os"
	"path"
	"regexp"

	"github.com/spf13/cobra/doc"
)

type RegRepl struct {
	Regex *regexp.Regexp
	Repl  string
}

func writeRegexRepl(file string, repls ...RegRepl) error {
	bytes, err := ioutil.ReadFile(file)
	if err != nil {
		return err
	}

	data := string(bytes)

	for _, r := range repls {
		data = r.Regex.ReplaceAllString(data, r.Repl)
	}

	return ioutil.WriteFile(file, []byte(data), cm.DefaultFileModeFile)

}

func fixFiles(files []string) {

	var regexAutoDate = regexp.MustCompile(`(.*Auto generated by.*)on.*`)

	const codeVar = `[a-zA-Z0-9_\-:.$+/|{}<> ]`
	const codeVarNS = `[a-zA-Z0-9_\-:.$+/|{}<>]`

	var regexCode = regexp.MustCompile(strs.Fmt(`'(%s+|%s{2,}%s*)'`, codeVarNS, codeVarNS, codeVar))
	var regexListItem = regexp.MustCompile(`•`)

	for _, f := range files {

		err := writeRegexRepl(f,
			RegRepl{Regex: regexCode, Repl: "`$1`"},
			RegRepl{Regex: regexListItem, Repl: "-"},
			RegRepl{Regex: regexAutoDate, Repl: "$1"})

		cm.AssertNoErrorPanic(err, "Replacement failed.")
	}
}

func main() {

	root, err := git.Ctx().Get("rev-parse", "--show-toplevel")
	cm.AssertNoErrorPanic(err, "Could not root dir.")

	docRoot := path.Join(root, "docs", "dialog")

	log, err := cm.CreateLogContext(false)
	cm.AssertNoErrorPanic(err, "Could not create log")

	ctx := dcm.CmdContext{Log: log}
	cmd := cmd.MakeDialogCtl(&ctx)

	err = os.RemoveAll(docRoot)
	cm.AssertNoErrorPanic(err, "Remove failed.")
	err = os.Mkdir(docRoot, cm.DefaultFileModeDirectory)
	cm.AssertNoErrorPanic(err, "Mkdir failed.")

	err = doc.GenMarkdownTree(cmd, docRoot)
	cm.AssertNoErrorPanic(err, "Generating CLI Dialog Doc failed.")

	files, err := cm.GetFiles(docRoot, nil)
	cm.AssertNoErrorPanic(err, "Getting files failed.")

	fixFiles(files)
}
