version: 1
urls:
  # As a demonstration, but here not used as we use treefmt with Nix.
  # - https://github.com/gabyx/githooks-shell.git@main
  # - https://github.com/gabyx/githooks-docs.git@main
  # - https://github.com/gabyx/githooks-configs.git@main
