language: go
os: linux
dist: bionic

go:
  - 1.15.8

services:
  - docker

install: skip

jobs:
  allow_failures:
    - name: coverage

  include:
    - os: linux
      name: coverage
      env:
        - TEST_INSTANCE=test-coverage
        - COVERALLS_TOKEN=$COVERALLS_TOKEN
    - os: linux
      env: TEST_INSTANCE=test-testsuite
    - os: windows
      env: TEST_INSTANCE=test-windows
    - os: linux
      env: TEST_INSTANCE=test-alpine
    - os: linux
      env: TEST_INSTANCE=test-alpine-user
    - os: linux
      env: TEST_INSTANCE=test-alpine-nolfs
    - os: linux
      env: TEST_INSTANCE=test-corehookspath
    - os: linux
      env: TEST_INSTANCE=test-whitespace
    - os: linux
      env: TEST_INSTANCE=test-rules

script:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sh "tests/${TEST_INSTANCE}.sh"
