sudo:
  - required
services:
  - docker
install: skip

script:
  - sh "tests/${TEST_INSTANCE}.sh"

env:
  - TEST_INSTANCE=test-alpine-go
  - TEST_INSTANCE=test-alpine-nolfs-go
  - TEST_INSTANCE=test-corehookspath-go
  - TEST_INSTANCE=test-whitespace-go
  - TEST_INSTANCE=test-rules
