language: go

go:
  - 1.15.6

services:
  - docker

install: skip

jobs:
  include:
  - os: windows
    env: TEST_INSTANCE=test-windows-go
  - os: linux
    env: TEST_INSTANCE=test-alpine-go
  - os: linux
    env: TEST_INSTANCE=test-alpine-go-user
  - os: linux
    env: TEST_INSTANCE=test-alpine-nolfs-go
  - os: linux
    env: TEST_INSTANCE=test-corehookspath-go
  - os: linux
    env: TEST_INSTANCE=test-whitespace-go
  - os: linux
    env: TEST_INSTANCE=test-rules
  - os: linux
    env: TEST_INSTANCE=test-coverage

script:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sh "tests/${TEST_INSTANCE}.sh"