language: go
os: linux
dist: bionic

services:
  - docker

install: skip

jobs:
  allow_failures:
    - name: coverage

  include:
    # only on PR and main
    - if: type = pull_request OR branch = main
      os: linux
      name: coverage
      env:
        - TEST_INSTANCE=test-coverage
        - COVERALLS_TOKEN=$COVERALLS_TOKEN

    # all tests only on PR
    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-testsuite

    - if: type = pull_request
      os: windows
      env: TEST_INSTANCE=test-windows

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-alpine

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-alpine-user

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-alpine-nolfs

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-corehookspath

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-whitespace

    - if: type = pull_request
      os: linux
      env: TEST_INSTANCE=test-rules

script:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash "tests/${TEST_INSTANCE}.sh"
