version: "3"

tasks:
  clean:
    cmds:
      - githooks/scripts/clean.sh

  build:
    cmds:
      - githooks/scripts/build.sh

  release-test:
    env:
      GORELEASER_CURRENT_TAG: v9.9.9
    cmds:
      - cd githooks &&
        goreleaser release --snapshot --clean --skip-sign --skip-publish --skip-validate
