version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  linux:
    resource_class: medium
    parameters:
      test:
        description: "The test script name"
        default: "test-alpine"
        type: string
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: bash tests/<<parameters.test>>.sh

  windows:
    parameters:
      test:
        description: "The test script name"
        default: "test-alpine"
        type: string
    executor:
      name: win/server-2022
      version: 2023.04.1
    steps:
      - checkout
      - run:
          command: "& 'C:/Program Files/Git/bin/sh.exe' tests/<<parameters.test>>.sh"

workflows:
  version: 2
  test-all:
    jobs:
      - linux:
          matrix:
            parameters:
              test:
                [
                  "test-alpine",
                  "test-alpine-nolfs",
                  "test-alpine-user",
                  "test-corehookspath",
                  "test-whitespace",
                  "test-testsuite",
                  "test-testsuite-podman",
                  "test-rules",
                ]
          filters: &filters
            branches:
              only: &task-branches
                - /feature\/.*/
                - /bugfix\/.*/
      - linux:
          matrix:
            parameters:
              test: ["test-coverage"]
          filters:
            branches:
              only:
                - /feature\/.*/
                - /bugfix\/.*/
                - "main"

      - windows:
          matrix:
            parameters:
              test: ["test-windows"]
          filters: *filters
